### ISSUE TITLE
Faceted Search

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#10]
@wsalesky We would like a faceted search for our Srophé app. 
There is an example where this has been executed really well: https://www.e-codices.unifr.ch/en/search/?aSelectedFacets=&sQueryString=&sSearchField=fullText&iResultsPerPage=20&sSortField=score 

We could provide the labels and paths for the facets.

**Comment by wsalesky** [comment]
@mMoliere yes, please give me a list of labels and xpaths and I will get that up and running.

**Comment by wsalesky** [comment]
@mMoliere There was a typo in the facet xpath. Country and City are now displaying as expected.

**Comment by wsalesky** [comment]
Bug is fixed. I still need to change the styling.
