### ISSUE TITLE
Persons: Add switch button for names

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#100]
@wsalesky We collect the names of persons in different scripts and transliterations. The `persName` element contains an `xml:lang` attribute with that information. We want to use this field to add a button inside the Names collapsible to switch between which forms of the names are displayed.

This is what Ronny wants the button to look like: 
![image](https://github.com/majlis-erc/srophe/assets/73166992/41971d3e-f45f-447f-bca0-030a9c3d377c)

**Comment by wsalesky** [comment]
@mMoliere this toggle should be in 'Names', 'Attested Names' ? Also, what happens to names that are @type='alternate' ?
The current xslt only displays the following name types: majlis-headword,canon,attested

In some of the example records I also see names with the type 'alternate' there may be other types? Also what happens for names with no/empty language attribute?

**Comment by mMoliere** [comment]
@wsalesky Yes, the toggle should be in 'Names' and 'Attested Names' (In 'Attested Names' the toggle only has the options Arabic and Hebrew). 

We will not display @type='alternate' in srophé, these names are just for reference. 

These four are the only types we are currently using.

Names without or with empty language attributes are not displayed.

**Comment by wsalesky** [comment]
@mMoliere Can you clarify which xml:lang codes will be shown by each option? 
I'm looking at this XML: https://github.com/majlis-erc/majlis-data/blob/main/data/persons/tei/7.xml#L65
I see: he-Latn, ar-Latn, ar

I will need a full list to filter correctly. Or I can do anything that starts with 'he' maps to Hebrew, anything that starts with 'ar' maps to Arabic?

**Comment by mMoliere** [comment]
@wsalesky 

If those values match exactly:

- "he": Hebrew
- "ar": Arabic

If value contains "Latn": English (e.g. he-Latn, ar-Lat)

**Comment by wsalesky** [comment]
@mMoliere Thanks! Should have that fix up shortly!

**Comment by wsalesky** [comment]
@mMoliere Is there a good record to test this on? That has all the variations?

**Comment by mMoliere** [comment]
@The most extensive so far is 11

**Comment by wsalesky** [comment]
Fix here: https://github.com/majlis-erc/srophe/pull/105

Let me know if this is how you want it to function, or if you want the toggle to hide the other languages when clicked.

**Comment by mMoliere** [comment]
@wsalesky This looks already great! I would like the different options to behave like this:

- English: contains "Latn"
- Arabic: contains "ar" or "Arab"
- Hebrew: contains "he" or "Hebr"

**Comment by wsalesky** [comment]
See update: https://github.com/majlis-erc/srophe/pull/106

**Comment by mMoliere** [comment]
@wsalesky Thanks. That works like a charm! Can you style the button like in the picture?

**Comment by wsalesky** [comment]
Opps, sorry about that! Here is the updates styles: 
https://github.com/majlis-erc/srophe/pull/109

**Comment by mMoliere** [comment]
I'm sorry, but I still can't see the updated style. I tried Srophé both in Chrome and in Firefox

**Comment by wsalesky** [comment]
@mMoliere This looks like it is now working on the site. Please confirm and close if you see it as well.

**Comment by mMoliere** [comment]
@wsalesky Works great!
