### ISSUE TITLE
Persons: References

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#102]
@wsalesky Please modify the footnote functionality from the original Srophé app for the MAJLIS persons. 

Basically a mouse over should be displayed whenever a user hovers over an element with a `source` attribute that has content. The mouse over displays the referenced `bibl` or `idno` elements.

The app should signal to the users that there is additional information by a suitable icon like a book with bookmark. I can provide an icon if you tell what file format you need.

**Comment by wsalesky** [comment]
A png file for the icon would be fine.

**Comment by mMoliere** [comment]
@wsalesky Let's try this one:
![Bookmark-Icon-small](https://github.com/majlis-erc/srophe/assets/73166992/e2518f31-526b-44d1-a703-e2238c9b6f10)

**Comment by wsalesky** [comment]
@mMoliere What record is a good test case?

**Comment by mMoliere** [comment]
@wsalesky 11.xml

**Comment by wsalesky** [comment]
Added here: https://github.com/majlis-erc/srophe/pull/107
Let me know if this is the functionality you want.

**Comment by wsalesky** [comment]
@mMoliere For the date of Birth and Place of birth, the xml looks like this: 
```
<date cert="" source="dnb">910</date>
<placeName ref="" cert="" source="dnb">Jerusalem</placeName>
```

There is no bibl or idno with a matching xml:id. Which I would need to make the refs work correctly.

**Comment by wsalesky** [comment]
See update here: https://github.com/majlis-erc/srophe/pull/122/

Also, this update fixes some code that got overwritten in the last update (my fault for not pulling the latest xslt before committing.)

**Comment by mMoliere** [comment]
@wsalesky With the update bibl references are displayed in the popups.

But when clicking on the popups, Srophé opens nonsensical URLs like "https://jalit.org/person/dnb". And the popups still display the string of the ID.

**Comment by mMoliere** [comment]
@wsalesky I'm sorry, I overlooked that part. You are right, the values in the source attributes were wrong.

If you look at 11.xml I added references to a bibl element, but the mouse-over is not working as expected:

![Bildschirmfoto 2024-04-29 um 19 35 23](https://github.com/majlis-erc/srophe/assets/73166992/64879e73-d2ec-4135-abcf-339a91fc633f)

**Comment by wsalesky** [comment]
@mMoliere They are expecting to find an xml:id attrubute. The idno does not have an xml:id attribute. If you want I can also add a lookup for the subtype attribute.

**Comment by mMoliere** [comment]
@wsalesky But I can't add the # when I'm choosing the references from the list in manuForma.

Noted, the idno elements need xml:ids

**Comment by wsalesky** [comment]
Sorry! It is a form issue then. And it does actually work without the xml:id. I tested it locally. I will fix how sources are added, to make sure they include the #. Can you make an issue for it? On Apr 29, 2024, at 2:13 PM, mMoliere ***@***.***> wrote:﻿
@wsalesky But I can't add the # when I'm choosing the references from the list in manuForma.
Noted, the idno elements need xml:ids

**Comment by wsalesky** [comment]
@mMoliere I think this can be closed. This has been added to manuForma here: https://github.com/majlis-erc/manuForma/pull/605
