### ISSUE TITLE
Update Browse Persons

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#103]
@wsalesky Please remove the name variants from browse view. See the image below:

![Screenshot 2024-02-14 at 12-14-37 JALit](https://github.com/majlis-erc/srophe/assets/73166992/942ccae7-be6d-48c7-b9b6-f88f5a1d8999)

Instead add the place of birth, date of birth, place of death and date of death in two columns. E.g. 

**Place of birth**: Jerusalem
**Date of birth:** 1001-1010     **Date of death**: 1070–1099

In this example there is no Place of death, because the field `//death/placeName` is empty.

**Comment by wsalesky** [comment]
Fix here: https://github.com/majlis-erc/srophe/pull/104

**Comment by mMoliere** [comment]
Thanks!
