### ISSUE TITLE
URLs

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#11]

**Comment by mMoliere** [comment]
@wsalesky The way MAJLIS-Srophé is wired right now, it will only display records that have the majlis.net domain. However, we want our records to use the jalit.org domain (majlis.net was a placeholder. To show the records to Nicolas and Hélène, I manipulated the files.) Can you adjust the settings in MAJLIS-Srophé?

**Comment by wsalesky** [comment]
@mMoliere This should be fixed. Please check and let me know.

**Comment by mMoliere** [comment]
@wsalesky So far, is doesn't work. I can see that you changed a file. The webhook is working. But somehow the file on the staging server is not being updated. For now, I manually changed the file on the server.
