### ISSUE TITLE
File not displayed

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#110]
@wsalesky I am working on works and I want to test my edits to the template. But I can't open the test file. "test-1.xml"

The idno looks correct to me: https://jalit.org/work/test-1

What am I missing?

**Comment by wsalesky** [comment]
@mMoliere Can you clarify? Where are you trying to open it? In manuForma? On the website?

**Comment by mMoliere** [comment]
@wsalesky In Srophé

**Comment by wsalesky** [comment]
@mMoliere Fixed. It was a line in the repo-config.xml file.
