### ISSUE TITLE
White-space handling

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#131]
@wsalesky In the Credits section, there is space character before a comma. It would be quite painful to eliminate this in the source files (even with regular expressions you can't be 100% sure that you get everything.) Could you try to modify how white-space is handled in Srophé to fix this?

![Screenshot 2024-04-29 at 19-38-36 Yešuʿa ben Yehuda](https://github.com/majlis-erc/srophe/assets/73166992/9a04bc93-2bc2-4670-9bf2-1f4fb1f0f07b)

**Comment by wsalesky** [comment]
@mMoliere Which record? All of them?

**Comment by mMoliere** [comment]
@wsalesky Yes, it seems to be a problem with all the records we have created so far.

**Comment by wsalesky** [comment]
Fixed here: https://github.com/majlis-erc/srophe/pull/133

**Comment by mMoliere** [comment]
Thanks!
