### ISSUE TITLE
Display full bibl records inside Persons, Manuscripts etc.

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#132]
@wsalesky I don't know how complicated it is to implement this. But in Syriaca you seem to have accomplished something very similiar: Display the information about publications in a bibliographic style. To me it seems that the main difference is that person records etc. in the MAJLIS project only contain a link to the imported Zotero record that would have to be pulled in and then transformed.

**Comment by wsalesky** [comment]
See: https://github.com/majlis-erc/srophe/pull/142
