### ISSUE TITLE
Persons Bug

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#137]
@wsalesky There seems to be a problem with the persons record 11.xml causing the following error message:

> exerr:ERROR Exception while transforming node: Too many nested template or function calls. The stylesheet may be looping. [at line 44, column 1] …

I believe it is connected with the type attribute value "attested". This attribute value triggers a dedicated collapsible to be displayed. I thought that I had solved the problem with my last update, but now the problem is back.

Could you take a look?

**Comment by wsalesky** [comment]
I think this is fixed here: https://github.com/majlis-erc/srophe/pull/138
I'm not getting an error locally.

**Comment by mMoliere** [comment]
@wsalesky I'm afraid the error is there. And it affects only 11.xml

**Comment by wsalesky** [comment]
Okay. I will investigate.

**Comment by wsalesky** [comment]
See: https://github.com/majlis-erc/srophe/pull/139
