### ISSUE TITLE
Fix links

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#148]
@wsalesky In JALit not all the links referencing other records or entities are functional.

E.g. 
![Screenshot 2024-05-10 at 11-06-17 Kitāb al-Tawriya](https://github.com/majlis-erc/srophe/assets/73166992/f47f9851-0814-4735-a797-a1e858208d2a)

![Screenshot 2024-05-10 at 11-16-23 St  Petersburg National Library of Russia Yevr -Arab  I 756](https://github.com/majlis-erc/srophe/assets/73166992/fd8daf1c-d979-4016-84a7-830326c725c2)

Is that something that can be sorted in one place of the code or do you need a list?

**Comment by wsalesky** [comment]
@mMoliere Sorry, can you give me more details? Which links are not working?

**Comment by mMoliere** [comment]
@wsalesky So far, I have seen that the links to _authors_ don't work in **manuscripts** and **works** records.

**Comment by wsalesky** [comment]
@mMoliere Just to save time, can you put links to a few problematic records here, so I do not have to go searching for them? Thanks!

**Comment by wsalesky** [comment]
@mMoliere  Please test this fix: https://github.com/majlis-erc/srophe/pull/152
