### ISSUE TITLE
Faceted search display issue

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#150]
@wsalesky In the faceted search of manuscripts the string "National Library of Russia" is displayed twice. I believe there may be an issue with the handling of white-space. (In the smaller group of files the string has an indent in its middle.)

![Screenshot 2024-05-21 at 09-18-28 JALit](https://github.com/majlis-erc/srophe/assets/73166992/e12e886a-5e39-42c8-9d57-83db2c9b1d69)

**Comment by wsalesky** [comment]
fixed here: https://github.com/majlis-erc/srophe/pull/151
