### ISSUE TITLE
Specify locus information in manuscripts

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#153]
@wsalesky information about the locus of texts should be more specific. 

Now, Srophé summarily gives the <locus> with the prefix "ff." It should be specific and give "f." when locus only gives a single folio page and "ff." when there are more than one.

See this example (251.xml):

![Screenshot 2024-05-27 at 15-13-16 St  Petersburg National Library of Russia Yevr -Arab  I 1427](https://github.com/majlis-erc/srophe/assets/73166992/1421a5f8-5966-4d29-803c-eebad3abca0a)

**Comment by wsalesky** [comment]
@mMoliere Can you clarify, by telling me what the TEI looks like for the two cases? Thanks

**Comment by mMoliere** [comment]
@wsalesky In the example from the screenshot (case "f.") the locus element looks like this: `<locus from="100v"/>`. In the case "ff." it looks like this: `<locus from="100v" to="101r"/>`

**Comment by wsalesky** [comment]
See here: https://github.com/majlis-erc/srophe/pull/162

**Comment by mMoliere** [comment]
@wsalesky This fix has not solved the problem.

**Comment by wsalesky** [comment]
@mMoliere how about now?

**Comment by mMoliere** [comment]
@wsalesky Thanks!
