### ISSUE TITLE
Style MSS joins

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#154]
@wsalesky "f." or "ff."  should only appear if <citedRange> has content.

Also, the link should be hidden. Clicking on the shelfmark should lead to the referenced MS entry.

![Screenshot 2024-05-27 at 15-22-41 St  Petersburg National Library of Russia Yevr -Arab  I 3570](https://github.com/majlis-erc/srophe/assets/73166992/41eab9cc-c854-4e00-86d0-26badeed6972)

**Comment by wsalesky** [comment]
@mMoliere TEI element?

**Comment by mMoliere** [comment]
@wsalesky The field Manuscript join consists of these TEI tags:

```
<bibl>
<idno type="manuscript-join">Yevr.-Arab. I 1751</idno>
<ptr target="https://jalit.org/manuscript/216"/>
</bibl>
```

**Comment by wsalesky** [comment]
See: https://github.com/majlis-erc/srophe/pull/163
