### ISSUE TITLE
Add sub-section to bibliography

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#155]
@wsalesky For manuscripts, please add a sub-section to bibliography titled "Reproductions" (The other bibliographical items is listed in the new sub-section "General bibliography"). Its contents is the following content (E.g. 415.xml):

```
<additional>
<surrogates>
<listBibl>
<bibl>
<title>Digital image online</title>
<publisher>National Library of Israel</publisher>
<ptr target="https://www.nli.org.il/he/discover/manuscripts/hebrew-manuscripts/viewerpage?vid=MANUSCRIPTS&docid=PNX_MANUSCRIPTS990001517970205171"/>
</bibl>
</listBibl>
</surrogates>
```

**Comment by wsalesky** [comment]
Update here: https://github.com/majlis-erc/srophe/pull/156
