### ISSUE TITLE
Consolidate double persons, places, and works

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#160]
@wsalesky In the manuscripts, we display the persons, places, and works mentioned in the descriptions in an extra menu. Right now, these menus display every instance of these entities. What we want is that each of them is only mentioned once.

This screenshot is from 514.xml

![Screenshot 2024-07-15 at 12-01-03 St  Petersburg National Library of Russia Yevr -Arab  I 19](https://github.com/user-attachments/assets/e97c9590-d145-4378-95ba-1373333e1ed5)

**Comment by wsalesky** [comment]
See fix: https://github.com/majlis-erc/srophe/pull/161

**Comment by mMoliere** [comment]
@wsalesky That fix has not solved the problem.

**Comment by wsalesky** [comment]
@mMoliere how about now?

**Comment by mMoliere** [comment]
@wsalesky That worked. Thank you!
