### ISSUE TITLE
Person: Add collapsible for associated work entries

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#164]
@wsalesky Please add another collapsible in the Persons entries for Work entries that are associated through the `author` identifiers they contain.

This is what we think the collapsible should look like:

![JALit Yešuʿa ben Yehuda FINAL](https://github.com/user-attachments/assets/e2942c0a-a62e-4621-8b21-9cc19fa63ffd)

Each work entry has its own row. They give the original title and then the English title in brackets.

For instance the work entry 12.xml contains the following information:

```
<title xml:lang="en" type="majlis-headword" xml:id="title-1">Introduction to the Commentary on the Book of Deuteronomy</title>
<title xml:lang="he" type="majlis-headword" xml:id="title-2">הקדמה לספר פרוש דברים</title>
<author ref="https://jalit.org/person/4">Yefet ben ʿElī</author>
```

` <author ref="https://jalit.org/person/4">` associates the work entry with the person entry Yefet ben ʿElī

<title xml:lang="he" type="majlis-headword" xml:id="title-2">הקדמה לספר פרוש דברים</title> gives us the title in the original language

<title xml:lang="en" type="majlis-headword" xml:id="title-1">Introduction to the Commentary on the Book of Deuteronomy</title> gives us the English title.

`@type="majlis-headword"` indicates the canonical title.

**Comment by wsalesky** [comment]
@mMoliere To clarify, you want to dynamically pull in the related works based on the author ref?

**Comment by mMoliere** [comment]
@wsalesky Yes, exactly

**Comment by mMoliere** [comment]
@wsalesky Do you have an update on this?

**Comment by wsalesky** [comment]
@mMoliere I will try to get to it this week.

**Comment by mMoliere** [comment]
@wsalesky We don't want to display references to manuscripts, we want references to associated **work** entries.

**Comment by wsalesky** [comment]
@mMoliere Where in the record do you want the works menu to be displayed?

**Comment by wsalesky** [comment]
@mMoliere See this pull request: https://github.com/majlis-erc/srophe/pull/194

**Comment by mMoliere** [comment]
@wsalesky Beautiful! Thanks!
