### ISSUE TITLE
Adjust sorting of manuscripts

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#166]
@wsalesky In the manuscript index the items are currently not sorted in the way users expect them:

![Screenshot 2024-07-19 at 12-28-24 JALit](https://github.com/user-attachments/assets/8fb31f58-3930-46f6-8c35-e7874f445aa1)

The numbers in the shelfmarks cause the entries to be sorted alphabetically: 1, 10, 100, 101, 102 …

But what we want that shelfmarks be sorted numerically: 1, 2, 3, 4, …, 10, …, 100, 101, 102 …

**Comment by mMoliere** [comment]
@wsalesky Have you had a chance to consider this? 

The different components of the sheldman have their own elements. E.g.:

```
<msIdentifier>
                        <country>Great Britain</country>
                        <settlement>London</settlement>
                        <repository>British Library</repository>
                        <collection>Or.</collection>
                        <idno>10599</idno>
                        <altIdentifier type="old">
                            <idno>Gaster Ms. 1448</idno>
                        </altIdentifier>
                    </msIdentifier> 
```

**Comment by wsalesky** [comment]
@mMoliere You want to sort by shelf # before alphabetical title?

**Comment by mMoliere** [comment]
@wsalesky Yes

**Comment by wsalesky** [comment]
Some of these have letters: 2581B.02,  2581B.07, 2581B.14 which makes it impossible to treat them all as numbers. Should I just ignore any idno's with letters? Or do you want to do something else with those?

**Comment by mMoliere** [comment]
@wsalesky Let's ignore these. They should not bother us in the grand scheme of things.

**Comment by mMoliere** [comment]
@wsalesky Thank you for the update. It seems that it leads to an error: "HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/majlis/manuscripts/index.html: An unknown error occurred: null"
