### ISSUE TITLE
Manuscripts: Hide work URLs and activate them

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#168]
@wsalesky Please hide work URLs and activate them, currently they don't lead onto the associated work entries.

![Screenshot 2024-07-19 at 12-41-00 St  Petersburg National Library of Russia Yevr -Arab  I 19](https://github.com/user-attachments/assets/1541ed41-5d50-4cae-8699-d4e8b8f5626f)

**Comment by wsalesky** [comment]
@mMoliere 
See: https://github.com/majlis-erc/srophe/pull/170

**Comment by mMoliere** [comment]
@wsalesky Thanks! Works great!
