### ISSUE TITLE
Manuscripts: Show author only once

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#175]
@wsalesky In the preview pane at the top: if the name of an author repeats, display it only once.

This example is from 514.xml

![Screenshot 2024-08-27 at 15-53-30 St  Petersburg National Library of Russia Yevr -Arab  I 19](https://github.com/user-attachments/assets/5d0df94a-6abe-4cf3-adb2-94efe87f81e8)

**Comment by wsalesky** [comment]
See: https://github.com/majlis-erc/srophe/pull/185
