### ISSUE TITLE
Manuscripts: Alphabetize entity lists

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#176]
@wsalesky Alphabetize the entity lists (names, places, and texts) after the preview pane.

This example is from 514.xml

![Screenshot 2024-08-27 at 15-55-45 St  Petersburg National Library of Russia Yevr -Arab  I 19](https://github.com/user-attachments/assets/ddda986b-ce6c-453a-b7e3-a16e6364a0c7)

**Comment by wsalesky** [comment]
See: https://github.com/majlis-erc/srophe/pull/185
