### ISSUE TITLE
Manuscripts: Titles don't link to work entries

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#177]
@wsalesky The titles in the Content collapsible don't link to work entries. On the other hand, the titles in the preview under the shelfmark do link. This example is from 514.xml

![Screenshot 2024-09-05 at 16-59-27 St  Petersburg National Library of Russia Yevr -Arab  I 19](https://github.com/user-attachments/assets/ee61634a-c638-4fe7-93b8-96ab0c2f954c)

**Comment by wsalesky** [comment]
See: https://github.com/majlis-erc/srophe/pull/185
