### ISSUE TITLE
Replace Srophé logo 

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#178]
@wsalesky Please replace the Srophé logo in the footer of entries and other sites with JALit logo. Also adjust the color of the line to the JALit color. 
![Screenshot 2024-09-05 at 17-03-13 St  Petersburg National Library of Russia Yevr -Arab  I 19](https://github.com/user-attachments/assets/900b336a-a5fb-4561-85da-4a6000f14673)

**Comment by wsalesky** [comment]
See: https://github.com/majlis-erc/srophe/pull/185
