### ISSUE TITLE
Remove superfluous keyboards

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#179]
@wsalesky We noticed there are two sets of keyboards. The correct one is inside the search bar. And another, deprecated one is on the right.

![Screenshot 2024-09-05 at 17-11-48 JALit](https://github.com/user-attachments/assets/e4d9f3ef-32df-4558-93ee-702de016a248)
![Screenshot 2024-09-05 at 17-11-35 JALit](https://github.com/user-attachments/assets/2420fc40-46eb-4e95-a2a7-42a16da37fce)

**Comment by wsalesky** [comment]
See: https://github.com/majlis-erc/srophe/pull/185
