### ISSUE TITLE
Print records

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#18]

**Comment by mMoliere** [comment]
@wsalesky The manuscript records have a button for printing at the top.

From my perspective, making this button functional would entail the following layout modifications:

- The boxes containing the elements are restyled to display no shadows.
- The collapsible headlines are displayed as headlines; followed by their contents.
- The buttons for Persons, Works, Places and the navigation bar below that are hidden.

**Comment by wsalesky** [comment]
@mMoliere Do you want the entities lists (persons, places, and works) displayed or hidden for the print version?

**Comment by wsalesky** [comment]
Done!
