### ISSUE TITLE
Manuscripts: Joins don't link

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#180]
@wsalesky The joins don't link to the entries.

Example from 308.xml

![Screenshot 2024-09-06 at 11-16-04 St  Petersburg National Library of Russia Yevr -Arab  I 82](https://github.com/user-attachments/assets/f2759972-046e-4870-b283-16408e36cae3)

```
<ab type="codicological-definition">
<objectType rend="vertical-rectangle" style="codex">Single manuscript</objectType>
<listBibl>
<bibl>
<idno type="">Yevr.-Arab. I 86</idno>
<ptr target="https://jalit.org/manuscript/306"/>
</bibl>
<bibl>
<idno type="manuscript-join">Yevr.-Arab. I 87</idno>
<ptr target="https://jalit.org/manuscript/305"/>
</bibl>
</listBibl>
</ab>
```

**Comment by wsalesky** [comment]
See: https://github.com/majlis-erc/srophe/pull/185
