### ISSUE TITLE
Manuscripts: Activate some links in bibliography

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#181]
@wsalesky I know that we asked you to deactivate the links in the bibliography. However, we want some entries to link to **external sites** where we can view other descriptions of the manuscripts or scans. One way to solve this problem, is to add a test in the stylesheet whether a link (`ptr`) contains the string "https://jalit.org/"

Example from 308.xml:

![Screenshot 2024-09-06 at 11-20-11 St  Petersburg National Library of Russia Yevr -Arab  I 82](https://github.com/user-attachments/assets/183eeec2-4a84-427f-be01-6f9f1fd9fef9)

And this is the TEI code:

```
<additional>
<surrogates>
<listBibl>
<bibl>
<title>Digital image online</title>
<publisher>National Library of Israel</publisher>
<ptr target="https://www.nli.org.il/he/discover/manuscripts/hebrew-manuscripts/viewerpage?vid=MANUSCRIPTS&docid=PNX_MANUSCRIPTS990001384150205171"/>
</bibl>
</listBibl>
</surrogates>
<listBibl>
<bibl>
<title>
Paul B. Fenton, A handlist of Judeo-Arabic manuscripts in Leningrad. A tentative handlist of Judeo-Arabic manuscripts in the Firkovic Collections -רשימת כתבי-יד בערבית-יהודית בלנינגרד: רשימה ארעית של כתבי-יד בערבית-יהודית באוספי פירקוביץ (Jerusalem: Ben-Zvi Institute, 1991).
</title>
<ptr target="https://jalit.org/bibl/CDYNP8XA"/>
</bibl>
<bibl>
<title>Ktiv</title>
<ptr target="https://web.nli.org.il/sites/NLIS/he/ManuScript/Pages/Item.aspx?ItemID=PNX_MANUSCRIPTS990001384150205171"/>
</bibl>
</listBibl>
</additional>
```

**Comment by wsalesky** [comment]
Fixed here: https://github.com/majlis-erc/srophe/pull/184

**Comment by wsalesky** [comment]
See: https://github.com/majlis-erc/srophe/pull/185
