### ISSUE TITLE
Manuscripts: Hide work entry links

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#182]
@wsalesky Please hide the link in brackets following the title inside the Content collapsible. But the link should remain functioning.
![Screenshot 2024-09-06 at 11-33-49 St  Petersburg National Library of Russia Yevr -Arab  I 82](https://github.com/user-attachments/assets/081e5fac-51d7-4fc9-ac9a-f242cc849971)

**Comment by wsalesky** [comment]
@mMoliere please include link to example record.

**Comment by wsalesky** [comment]
Fixed. See here: https://github.com/majlis-erc/srophe/pull/183

**Comment by wsalesky** [comment]
See: https://github.com/majlis-erc/srophe/pull/185
