### ISSUE TITLE
Suggested Citation Bug

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#195]
@wsalesky The Suggested Citation does not work as expected. In the entry types manuscript, person, and place it does not display the name of the record. And in the entry trype text it is not displayed at all.

Person 18.xml

![Screenshot 2024-10-28 at 09-59-50 Abraham al-Harzilānī](https://github.com/user-attachments/assets/ba7049cf-dc19-4a72-a353-81d8c397158a)

Text 38.xml

![Screenshot 2024-10-28 at 09-57-07 Zohar](https://github.com/user-attachments/assets/8c0bbc56-00a8-4973-9183-5cf1687739bd)

**Comment by wsalesky** [comment]
@mMoliere is this a new issue or has it always been this way? (I'm wondering if I changed something that was working.)

**Comment by mMoliere** [comment]
@wsalesky This is a new issue. Until last week the suggested citations worked fine.

**Comment by wsalesky** [comment]
@mMoliere whats the link for the second example?

**Comment by mMoliere** [comment]
@wsalesky https://manuforma-staging.jalit.org/exist/apps/majlis/work/38

**Comment by wsalesky** [comment]
See: https://github.com/majlis-erc/srophe/pull/196

**Comment by wsalesky** [comment]
@mMoliere what is missing? Credits tab? How to Cite? Both?

**Comment by mMoliere** [comment]
@wsalesky Both are still missing in Works.

**Comment by wsalesky** [comment]
@mMoliere This should do the trick:
https://github.com/majlis-erc/srophe/pull/200

**Comment by mMoliere** [comment]
@wsalesky Beautiful! Thank you
