### ISSUE TITLE
Works: Collapsible for associated manuscripts

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#202]
@wsalesky We want a collapsible for displaying associated manuscripts entries in the works records. (Similar to the feature you recently implemented for persons and their works. #164)

Essentially, Srophé should search for the identifier of the work inside the manuscripts collection and display the shelfmark (i.e. the first `title` element of the record) and the associated `locus` elements

I have already created the elements for the navigation in majlis.xsl which is commented out at the moment. https://github.com/majlis-erc/srophe/blob/93c12c9878452c066396a188f3c7293873c440f0/resources/xsl/majlis.xsl#L609-L612

**Comment by wsalesky** [comment]
Can I expect all of these to be in title/@ref ?
Example:
```
<msItem class="" xml:id="item-11">
                            <locus from="1r" to="183v"/>
                            <title ref="https://jalit.org/work/18">Book of Lights and Watchtowers</title>
                            <author ref="https://jalit.org/person/279">Yaʿqov ben Yiṣḥaq ha-Qirqisānī</author>
                            <textLang mainLang="ar" otherLangs=""/>
                            <incipit>
                                <locus from="" to=""/>
                                <quote xml:lang="ar-Hebr"/>
                            </incipit>
                            <explicit>
                                <locus from="" to=""/>
                                <quote xml:lang="ar"/>
                            </explicit>
                            <note xml:lang=""><p>Containing discourse 1, chapter 1; discourse 2, chapters 6, 9–11, 14–17, 22; discourse 3, chapters 3–7, 10–12, 15–17; discourse 5, chapter 23; discourse 6, chapter 3(?); discourse 7, chapters 13–14; discourse 9, table of contents and chapters 1–3, 6–9, 20–24; discourse 10, table of contents and chapters 1–10, 12–18, 48–49, 51–61, 63–66a; discourse 11, chapters 6–12, 19–20, 23–28; discourse 12, chapters 20–26, 29–32; discourse 13, chapters 6–9, 12–13. </p><p/></note>
                        </msItem>
```

**Comment by wsalesky** [comment]
Try this: https://github.com/majlis-erc/srophe/pull/213

**Comment by mMoliere** [comment]
@wsalesky We love it! Now we would like to tweak the way the entries are ordered. As you can see in this example (works/21), the number 1903 is followed by 996, and then 3020. What we want is the sequence 996, 1903, 3020.

![Screenshot 2024-11-19 at 09-19-11 The Book of Grace (Levi b  Yefet)](https://github.com/user-attachments/assets/1c701336-7737-4a84-9502-b61ea838316e)

**Comment by wsalesky** [comment]
Update here: https://github.com/majlis-erc/srophe/pull/225

**Comment by mMoliere** [comment]
@wsalesky Thank you for the update. It seems that it leads to an error. E.g. work entry 12. (https://manuforma-staging.jalit.org/exist/apps/majlis/work/12): "HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/majlis/work/12: An unknown error occurred: null"

**Comment by wsalesky** [comment]
This should do the trick. https://github.com/majlis-erc/srophe/pull/227

**Comment by wsalesky** [comment]
@mMoliere looks fixed to me?

**Comment by mMoliere** [comment]
@wsalesky Yes, indeed
