### ISSUE TITLE
Add map to places browse site

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#212]
@wsalesky Please add a map view of places in the browse site. It should work much like the one on [Syriaca](https://syriaca.org/geo/browse.html?view=map). Users can choose between a List view and a Map view on the top of the page. Then the map or the list. The list view stays as it is now. The data for the coordinates may be found at `//location/geo`. The tooltip should display the name (`placeName[@type='majlis-headword']`).

Here is a very crude mockup.

![Screenshot 2024-11-08 at 19-03-56 Syriaca org web application](https://github.com/user-attachments/assets/c9100b05-98e8-46fa-9492-dd587d14412f)

**Comment by wsalesky** [comment]
See: https://github.com/majlis-erc/srophe/pull/214

**Comment by mMoliere** [comment]
@wsalesky It looks beautiful!

There are a couple of things to improve:

- Your pull request overwrote the changes I made to the places template in majlis.xsl. Could you restore them?
- When selecting the map on the places browse page: When you then go back (select "All") there is no more option to select the map again. This may be due to switching from `index.html` to `browse.html`

If possible make the following adjustments to the map page itself: 
- Deactivate the layer selection menu (nothing is displayed when you select one of other options)
- Deactivate or fix "Only places with coordinates are displayed"– again, nothing is displayed when you select it.
- Change the color of the pins to the green of our links.
- Deactivate the page selection menu at the bottom of the map page, since it has no function in this context.

**Comment by wsalesky** [comment]
See: 
https://github.com/majlis-erc/srophe/pull/215

This should address all issue except the color of the pins, which is more tricky to change, I'm leaving them blue for the moment

**Comment by mMoliere** [comment]
@wsalesky Thanks!
