### ISSUE TITLE
Map Error

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#232]
@wsalesky The map displays place entries that have no coordinates. **For example, place entry 8.xml.** My guess is that it obliquely assigns them the coordinates "0 0" which puts that before the coast of West Africa.
![Screenshot 2024-12-13 at 18-29-38 JALit](https://github.com/user-attachments/assets/6a51bcfc-cd88-494e-99e3-176f21fb5b6b)

**Comment by wsalesky** [comment]
See here: https://github.com/majlis-erc/srophe/pull/233
