### ISSUE TITLE
PR does not work for me

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#28]
@wsalesky I  try to merge my changes, but the PR I created now points to the original repository of srophe. (https://github.com/srophe/srophe/pull/44) Maybe I don't have sufficient rights. Maybe I overlooked something.

**Comment by wsalesky** [comment]
@mMoliere when doing the pull request, you will need to just make sure you select the majlis-ecr/srophe application as the repository you want to merge into. There is a select menu, or you can type it in. Did you do your work on a new branch? If so I can make the pull request for you. The current pull request, is pointing to the wrong repository.

**Comment by wsalesky** [comment]
@mMoliere I attempted to merge your branch (https://github.com/majlis-erc/srophe/tree/27-extend-manuscript-module) into the main branch, however, there are no changes on it.

**Comment by mMoliere** [comment]
@wsalesky That's weird. I will look into this.
