### ISSUE TITLE
Adapt mss output

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#42]
@wsalesky We have made quite some changes to the template which are not yet reflected in the mss output. I have prepared a list  of all collapsibles, the fields they contain and the XPath. It also specifies punctuation and connecting phrases in quotes. Brackets contain comments.

# Content

- **Folios** msDesc/msContents/msItem/locus/@from "–" msDesc/msContents/msItem/locus/@to
- **Title** msDesc/msContents/msItem/title
- **Author** msDesc/msContents/msItem/author
- **Language** msDesc/msContents/msItem/textLang/@mainLang and msDesc/msContents/msItem/textLang/@otherLangs

[transform attribute values: 

"ar" = "Arabic"
"he" = "Hebrew"
"en" = "English"
"he-Latn" = "Hebrew in Latin characters"
"ar-Latn" = "Arabic in Latin characters"
"ar-Hebr" = "Arabic in Hebrew characters"]

- **Incipit** msDesc/msContents/msItem/incipit/quote (msDesc/msContents/msItem/incipit/locus/@from "–" msDesc/msContents/msItem/incipit/locus/@to)
- **Explicit**  msDesc/msContents/msItem/explicit/quote (msDesc/msContents/msItem/explicit/locus/@from "–" msDesc/msContents/msItem/explicit/locus/@to)
- **Note** msDesc/msContents/msItem/note

# Codicological definition

- **Manuscript type** msDesc/physDesc/ab/objectType
- **Format** msDesc/physDesc/ab/objectType/@rend
- **Book form** msDesc/physDesc/ab/objectType/@style

Manuscript join [enumerated] 

msDesc/physDesc/ab/listBibl/bibl/idno, "ff. " msDesc/physDesc/ab/listBibl/bibl/citedRange [Link to that record via msDesc/physDesc/ab/listBibl/bibl/ptr/@target]

# Codicology

- **Material** msDesc/physDesc/objectDesc/supportDesc/support/material 
- **Note** msDesc/physDesc/objectDesc/supportDesc/support/note
- **Extent** msDesc/physDesc/objectDesc/supportDesc/extent/measure
- **Dimensions** msDesc/physDesc/objectDesc/supportDesc/extent/dimensions/height " ✕ " msDesc/physDesc/objectDesc/supportDesc/extent/dimensions/width " mm" 
- **Foliation** [enumerated]  msDesc/physDesc/objectDesc/supportDesc/foliation/@rendition msDesc/physDesc/objectDesc/supportDesc/foliation
- **Collation** msDesc/physDesc/objectDesc/supportDesc/collation/formula " per quire. " msDesc/physDesc/objectDesc/supportDesc/collation/catchwords "." msDesc/physDesc/objectDesc/supportDesc/collation/note
- **Condition** msDesc/physDesc/objectDesc/supportDesc/condition/note
- **State of writing** msDesc/physDesc/objectDesc/supportDesc/condition/ab/@rend ". " msDesc/physDesc/objectDesc/supportDesc/condition/ab

- **Layout summary** msDesc/physDesc/objectDesc/layoutDesc/summary/desc "." msDesc/physDesc/objectDesc/layoutDesc/summary/note 

[The fields in <layout> can repeat.]

- **Folio range of layout** "ff. " msDesc/physDesc/objectDesc/layoutDesc/layout/locus/@from "–" msDesc/physDesc/objectDesc/layoutDesc/layout/locus/@to
- **Written lines** msDesc/physDesc/objectDesc/layoutDesc/layout/@writtenLines

- **Columns** msDesc/physDesc/objectDesc/layoutDesc/layout/@columns
- **Text block** msDesc/physDesc/objectDesc/layoutDesc/layout/dimensions/height " ✕ " msDesc/physDesc/objectDesc/layoutDesc/layout/dimensions/width " mm"

[the following two tags have no labels preceding them. Each is concluded with "."]

- msDesc/physDesc/objectDesc/layoutDesc/layout/metamark
- msDesc/physDesc/objectDesc/layoutDesc/layout/ab

- **Page layout** msDesc/physDesc/decoDesc/summary

- [new line, enumerated, but no label] msDesc/physDesc/decoDesc/decoNote/desc ". " msDesc/physDesc/decoDesc/decoNote/note

# Paleography

- **Summary** msDesc/physDesc/handDesc/summary
- **Script** [enumerated] msDesc/physDesc/scriptDesc/scriptNote/@xml:lang ", " msDesc/physDesc/scriptDesc/scriptNote/@script ", " msDesc/physDesc/scriptDesc/scriptNote/@style ", "

msDesc/physDesc/scriptDesc/scriptNote/@rend

[new paragraph]

msDesc/physDesc/scriptDesc/scriptNote/note

**Hand** [enumerated]

- **Range of hand** msDesc/physDesc/handDesc/handNote/locus/@from "–" msDesc/physDesc/handDesc/handNote/locus/@to
- **Scribe** msDesc/physDesc/handDesc/handNote/persName
- **Place of origin** msDesc/physDesc/handDesc/handNote/placeName
- **Date of origin** msDesc/physDesc/handDesc/handNote/origDate
- **Ink** msDesc/physDesc/handDesc/handNote/@medium

[the following two tags have no labels preceding them.]

- msDesc/physDesc/handDesc/handNote/metamark
- msDesc/physDesc/handDesc/handNote/note

# Incodicated Documents [was Additions]

[each msDesc/physDesc/additions/list/item is enumerated but has no label.]

- msDesc/physDesc/additions/list/item/objectType ", ff. " msDesc/physDesc/additions/list/item/locus/@from "–" msDesc/physDesc/additions/list/item/locus/@to

[new paragraph]

- **Person mentioned**  msDesc/physDesc/additions/list/item/persName
- **Transcription** msDesc/physDesc/additions/list/item/quote
- **Translation** msDesc/physDesc/additions/list/item/ab
- **Note** msDesc/physDesc/additions/list/item/note

# History

- **Summary** msDesc/history/summary

Provenance [enumerated]

- **Date** msDesc/history/provenance/date
- **Place** msDesc/history/provenance/placeName
- **Range of folios** msDesc/history/provenance/locus/@from "–" msDesc/history/provenance/locus/@to
- **Owner** msDesc/history/provenance/persName
- **Transcription** msDesc/history/provenance/quote
- **Stamp** msDesc/history/provenance/stamp
- **Note** msDesc/history/provenance/note

Acquisition

- **Date** msDesc/history/acquisition/date
- **Place** msDesc/history/acquisition/placeName
- **Range of folios** msDesc/history/acquisition/locus/@from "–" msDesc/history/acquisition/locus/@to
- **Owner** msDesc/history/acquisition/persName
- **Transcription** msDesc/history/acquisition/quote
- **Stamp** msDesc/history/acquisition/stamp
- **Note** msDesc/history/acquisition/note

# Heritage Data

[each msDesc/physDesc/accMat/list/item is enumerated but has no label.]

- [no label] msDesc/physDesc/accMat/list/item/note
- **Author** msDesc/physDesc/accMat/list/item/persName
- **Transcription** msDesc/physDesc/accMat/list/item/quote
- **Reference** msDesc/physDesc/accMat/list/item/bibl/title ", " msDesc/physDesc/accMat/list/item/bibl/citedRange

# Bibliography

[each bibl is enumerated]

msDesc/additional/listBibl/bibl/title ", " msDesc/additional/listBibl/bibl/citedRange

# How to cite

 /TEI/teiHeader/fileDesc/titleStmt/title /TEI/teiHeader/ ". In <emph>Digital Handbook of Jewish Authors Writing in Arabic</emph>, edited by Ronny Vollandt. Accessed " [today's date] ", " /TEI/teiHeader/fileDesc/publicationStmt/idno "."

**Comment by wsalesky** [comment]
@mMoliere What are you asking me to do here? Add these to config.xml? Something else? Thanks for the clarification.

**Comment by mMoliere** [comment]
@wsalesky Sorry for the confusion, I mean adapting majlis.xsl for displaying manuscript records in Srophé.

**Comment by wsalesky** [comment]
@mMoliere Sorry! I didn't notice this was in the srophe app repository. I will make those changes this week.

**Comment by wsalesky** [comment]
@mMoliere Can you let me know what records I can test these on?

**Comment by mMoliere** [comment]
@wsalesky In the mss folder, 2.xml is thé file the team has added the Most information to

**Comment by mMoliere** [comment]
@wsalesky I am afraid the error is still there.
