### ISSUE TITLE
Only display rows for filled out elements

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#46]
@wsalesky At the moment, Srophe displays rows and their labels if the TEI element in question is in the document – no matter if the element has content or not. This leads to many empty rows in the display:

![Screenshot 2023-09-25 at 19-51-27 London British Library Oriental 2523 1](https://github.com/majlis-erc/srophe/assets/73166992/f14827a3-0ff2-47f8-a630-20591960c8d8)

We would like Srophé to display rows and their labels only if the TEI element in question has content to display.

**Comment by mMoliere** [comment]
@wsalesky Thank you for the update. I'm afraid it is still not behaving in the way we want.

**Comment by wsalesky** [comment]
Hum, I will take another look.

**Comment by mMoliere** [comment]
@wsalesky Mostly, this works now. However, the image below shows a case where certain empty rows are still being displayed. Could this be triggered by the filled out element at the end of the element tree? The file is BNFAr1.xml
![Screenshot 2023-10-09 at 09-37-11 Paris BNF Ar  1](https://github.com/majlis-erc/srophe/assets/73166992/90bebdd4-9f16-4ce2-8e3c-b6733cbf0eb0)

**Comment by wsalesky** [comment]
Fixed here: https://github.com/majlis-erc/srophe/pull/53

**Comment by mMoliere** [comment]
@wsalesky Well done!
