### ISSUE TITLE
Add change log

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#52]
@wsalesky Please add the change log entries (`/TEI/teiHeader/revisionDesc/change`) to the Credits collapsable. The `who` attribute containing an abbreviated should draw the full name from the list of editors (`/TEI/teiHeader/fileDesc/titleStmt/editor/persName`) which also contains the relevant `xml:ids`.

An entry in XML like this:

`<change who="#mmoliere" when="23-10-09">Changed the binding description.</change>`

… should look this in Srophé: 

**Maximilian de Molière** (23-10-09): Changed the binding description.

The list of entries is introduced as: **Change log:**

And the citation that is already in  the Credits collapsable is introduced as: **Suggested citation:**

**Comment by wsalesky** [comment]
Resolved here: https://github.com/majlis-erc/srophe/pull/54

**Comment by mMoliere** [comment]
@wsalesky This looks great. All that is missing now is the 'when' attribute.

**Comment by wsalesky** [comment]
Resolved here: https://github.com/majlis-erc/srophe/pull/63

**Comment by mMoliere** [comment]
@wsalesky Great! 

Could you format the date into something more legible? Day Month Year, e.g. 20 October 2023

**Comment by wsalesky** [comment]
How is this: https://github.com/majlis-erc/srophe/pull/66
