### ISSUE TITLE
Paleography error

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#55]
@wsalesky In the Paleography collapsible, only the empty Summary row is displayed, whereas the values in `scriptNote` are not visible (`<scriptNote xml:lang="arabic" script="naskh" style="" rend="calligraphic">`).
 The file is OxfordLaufOr258.xml
![Screenshot 2023-10-13 at 18-43-26 Oxford Bodleian Library MS Laud  Or  25](https://github.com/majlis-erc/srophe/assets/73166992/abecc455-30de-42c8-9ba1-ba551ad0a296)

**Comment by wsalesky** [comment]
For all records? Or one in particular?

**Comment by mMoliere** [comment]
@wsalesky This is the only file where I observed this. It may be due to that only the attributes are filled out.

**Comment by wsalesky** [comment]
Can you give me the link?

**Comment by wsalesky** [comment]
Fixed here: https://github.com/majlis-erc/srophe/pull/59

**Comment by mMoliere** [comment]
@wsalesky This is much better. All that is missing now is the `xml:lang` attribute. Please capitalize the first letter, so that "arabic" becomes "Arabic" etc. in the output.

**Comment by wsalesky** [comment]
@mMoliere This is a data issue, it is 'arabic' in the data but should be 'ar'  Did this come from the forms?

**Comment by mMoliere** [comment]
@wsalesky You are right, I will correct this.

**Comment by wsalesky** [comment]
@mMoliere was it from the form? Because that means the forms are putting in the wrong value, which would be a bug.

**Comment by mMoliere** [comment]
@wsalesky Indeed, it's in the list of values I defined in the schema.

**Comment by wsalesky** [comment]
@mMoliere Okay. Just wanted to make sure the forms were not inserting the wrong thing.
