### ISSUE TITLE
Locus

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#57]
@wsalesky Srophé should display the attributes values of `<locus from="9r" to="22v">` as "fols. 9r–22v". In case that there is only `<locus from="9r" to="">` or `<locus from="9r">` display "fol. 9r". It is to be displayed after `<title>`.

The Content collapsible should display in brackets, e.g.  "(fols. 9r–22v)" and after `<title>`.

**Comment by wsalesky** [comment]
@mMoliere Can I have some test cases to test the output on?

**Comment by mMoliere** [comment]
@wsalesky Sorry, of course: OxfordLaufOr258.xml and SinaiAr2.xml are test cases

**Comment by wsalesky** [comment]
Fixed here: https://github.com/majlis-erc/srophe/pull/74

**Comment by mMoliere** [comment]
@wsalesky Sorry for the slow reaction time. For both test files the output is unchanged – `locus` is not being displayed

**Comment by wsalesky** [comment]
The file did not update on the server for some reason. This is now fixed.
