### ISSUE TITLE
Adjust direction

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#60]
@wsalesky Please adjust the display direction of the `quote` element to its `xml:lang` attribute. If the attribute contains the following values the direction is to be rtl:

- he
- ar

**Comment by wsalesky** [comment]
@mMoliere test records? (This should already work, so there is clearly a bug somewhere.)

**Comment by mMoliere** [comment]
@wsalesky Sorry, of course: SinaiAr2.xml

**Comment by wsalesky** [comment]
Fixed here. Note to self: dir attribute only works on block elements, not spans.
