### ISSUE TITLE
Only display collapsibles with content

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#62]
@wsalesky Over time the manuscript records will fill with data, but we will not have information in every area of interest for every manuscript.

We only want to display those collapsibles that have some form of content. – The same goes for the selection menu at the top.

**Comment by wsalesky** [comment]
Resolved: https://github.com/majlis-erc/srophe/pull/65

**Comment by mMoliere** [comment]
@wsalesky Beautiful!
