### ISSUE TITLE
Add all titles to the preview section

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#67]
@wsalesky The preview section, immediatelly following the shelfmark, only displays the first `title` element. We want all of them, separated by commas

E.g.: "Genesis, Exodus, Leviticus, Deuteronomy, Daniel"
![Screenshot 2023-10-20 at 19 01 10](https://github.com/majlis-erc/srophe/assets/73166992/b2bc2b82-077e-43f4-b23b-48c7359921f0)

Example file: SinaiAr2.xml

**Comment by wsalesky** [comment]
Fixed here: https://github.com/majlis-erc/srophe/pull/73
