### ISSUE TITLE
Credits: team member not displayed

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#79]
@wsalesky In 293.xml in the Credits collapsible the first team member is not being displayed.
![Bildschirmfoto 2023-12-14 um 18 21 38](https://github.com/majlis-erc/srophe/assets/73166992/1bfed92e-75d1-46ad-9aa9-bb23889f07ed)

**Comment by wsalesky** [comment]
@mMoliere How does this look: https://manuforma-staging.jalit.org/exist/apps/majlis/manuscript/6

**Comment by mMoliere** [comment]
@wsalesky Thank you!
