### ISSUE TITLE
Revamp Credits

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#80]
@wsalesky We want to give more detailed information in the Credits and move the Suggested Citation.

1. Before the changelog, the project details will be displayed. These are the labels and their fields:

Project: `title level="m"`

<no label> `edition`

Principal investigator: `editor role="general"`

Associate researcher:  `editor role="contributor"`

2. The Suggested Citation is moved outside of the collapsibles. It is positioned at the very end of the entry.

**Comment by wsalesky** [comment]
See: https://manuforma-staging.jalit.org/exist/apps/majlis/manuscript/6
