### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#83]
@wsalesky In the "credits" section, the fields "Principal investigator:" and "Associate researcher:" have no content. The ought to reference the TEI fields `titleStmt/principal` and `titleStmt/editor` respectively.

The example below is from 293.xml

![Screenshot 2024-01-22 at 09-36-09 St  Petersburg National Library of Russia Yevr -Arab  I 108](https://github.com/majlis-erc/srophe/assets/73166992/3b7fca54-68ce-4e6c-aa8d-9879a4d35816)

**Comment by wsalesky** [comment]
Fixed here: https://github.com/majlis-erc/srophe/pull/89
