### ISSUE TITLE
Bibliography links

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#84]
@wsalesky Certain entries in the bibliography reference external databases in `ptr/@target`

That means that in these cases we want the following modifications:

1. Delete the trailing comma (see image below)
2. Create a link from `ptr/@target` – opens in a new window

This example is from 293.xml

![Screenshot 2024-01-22 at 09-37-41 St  Petersburg National Library of Russia Yevr -Arab  I 108](https://github.com/majlis-erc/srophe/assets/73166992/0cf26089-a651-459e-bd9d-522d84bb469f)

**Comment by wsalesky** [comment]
Fixed here: https://github.com/majlis-erc/srophe/pull/90
