### ISSUE TITLE
Notes don't line up

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#85]
@wsalesky Please line up the notes across different sections with the other content. Example from 293.xml 

Also. `note` in Heritage Data needs the "Note:" label.

![Screenshot 2024-01-22 at 09-46-07 St  Petersburg National Library of Russia Yevr -Arab  I 108](https://github.com/majlis-erc/srophe/assets/73166992/78c5b9e5-ad4a-400d-a079-ec5fb73ac555)

**Comment by wsalesky** [comment]
Fixed here: https://github.com/majlis-erc/srophe/pull/91
