### ISSUE TITLE
Add author to "Referenced persons"

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#88]
@wsalesky The `author` field is missing from the list of referenced persons in 293.xml
![Screenshot 2024-01-22 at 10-25-58 St  Petersburg National Library of Russia Yevr -Arab  I 108](https://github.com/majlis-erc/srophe/assets/73166992/95dd4e5f-03cb-45b2-ac3b-2ea220540765)

**Comment by wsalesky** [comment]
Fixed here: https://github.com/majlis-erc/srophe/pull/94
