### ISSUE TITLE
Persons: Main menu displays names of empty collapsibles

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#99]
@wsalesky The main menu for the persons template displays names of empty collapsibles. This is probably due to the different structure of the persons records. For the manuscript records you were able to match one element per collapsible and then process its child elements. The person records are messier, because most elements are inside the person element. This means in majlis.xsl there is one large template that transforms creates of the collapsibles:

https://github.com/majlis-erc/srophe/blob/fbe872fa4d85f2fe4cee926ff3693684251647b0/resources/xsl/majlis.xsl#L626

However, this causes the problem I mentioned above: the names of collapsibles are displayed in the main menu even though they elements they reference are empty. https://github.com/majlis-erc/srophe/blob/fbe872fa4d85f2fe4cee926ff3693684251647b0/resources/xsl/majlis.xsl#L460 I could not figure out how to solve this.

The collapsibles where this problem could arise are:

- Names
- Attested names
- Biography
- Bibliography
- Linked Open Data

Here is an example (11.xml)

![Screenshot 2024-02-13 at 10-08-43 Yešuʿa ben Yehuda](https://github.com/majlis-erc/srophe/assets/73166992/0f1fa498-957b-48c8-9c1e-eedb7368fa4f)

**Comment by wsalesky** [comment]
@mMoliere See here for fix: https://github.com/majlis-erc/srophe/pull/101

**Comment by mMoliere** [comment]
@wsalesky Thanks for the quick work!
